# Generated by Django 5.0.6 on 2026-09-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientgroup',
            name='category',
            field=models.CharField(choices=[('MSP', 'MSP'), ('FDP', 'FDP'), ('RP', 'RP'), ('REPORT', 'Report'), ('ESCALATION_MATRIX', 'Escalation Matrix')], max_length=20),
        ),
    ]
