# Generated by Django 5.0.6 on 2026-09-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_recipientgroup_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSPEscalationMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msp', models.CharField(choices=[('Egypro', 'Egypro'), ('Camusat', 'Camusat'), ('Adrian', 'Adrian'), ('Kinde', 'Kinde'), ('Fireside', 'Fireside'), ('Soliton', 'Soliton'), ('Sovereign', 'Sovereign'), ('Optimax', 'Optimax'), ('Tetranet', 'Tetranet'), ('Corevantage', 'Corevantage')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MSPEscalationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Project Manager', 'Project Manager'), ('Technical Project Manager', 'Technical Project Manager'), ('Chief Operating Officer', 'Chief Operating Officer'), ('Chief Technical Officer', 'Chief Technical Officer'), ('Chief Executive Officer', 'Chief Executive Officer')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emails.mspescalationmatrix')),
            ],
            options={
                'unique_together': {('matrix', 'role', 'email')},
            },
        ),
    ]
