# Generated by Django 5.0.6 on 2026-09-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_mspescalationmatrix_mspescalationemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='HODEscalationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('email',)},
            },
        ),
    ]
