# Generated by Django 5.0.6 on 2026-09-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_hodescalationemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientgroup',
            name='category',
            field=models.CharField(choices=[('MSP', 'MSP'), ('FDP', 'FDP'), ('RP', 'RP'), ('REPORT', 'Report')], max_length=20),
        ),
    ]
