# Generated by Django 5.0.6 on 2024-11-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='msp',
            field=models.CharField(choices=[('Egypro', 'Egypro'), ('Camusat', 'Camusat'), ('Adrian', 'Adrian'), ('Kinde', 'Kinde'), ('Fireside', 'Fireside'), ('Soliton', 'Soliton')], default=None, max_length=50, null=True),
        ),
    ]
