# Generated by Django 5.0.6 on 2024-11-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0002_alter_dispatch_msp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='close_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fdp_category',
            field=models.CharField(choices=[('None', 'None'), ('Fireside', 'Fireside'), ('Broadcom', 'Broadcom'), ('Optimax', 'Optimax'), ('BTN', 'BTN'), ('Com21', 'Com21'), ('Bens', 'Bens')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rp_category',
            field=models.CharField(choices=[('None', 'None'), ('Fireside', 'Fireside'), ('Broadcom', 'Broadcom'), ('Optimax', 'Optimax'), ('BTN', 'BTN'), ('Com21', 'Com21'), ('Bens', 'Bens')], default='None', max_length=50, null=True),
        ),
    ]
