# Generated by Django 5.0.6 on 2024-11-03 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0003_dispatch_close_image_alter_user_fdp_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='close_image',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='dispatch_image',
        ),
        migrations.CreateModel(
            name='DispatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dispatch_images/')),
                ('image_type', models.CharField(default='creation', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashauri.dispatch')),
            ],
            options={
                'verbose_name': 'Dispatch Image',
                'verbose_name_plural': 'Dispatch Images',
                'db_table': 'mashauri_dispatch_images',
            },
        ),
    ]
