# Generated by Django 5.0.6 on 2024-11-03 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0004_remove_dispatch_close_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchimage',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mashauri.dispatch'),
        ),
    ]
