# Generated by Django 5.0.6 on 2024-11-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0005_alter_dispatchimage_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='ec',
            field=models.CharField(choices=[('Steven Ogola', 'Steven Ogola'), ('Emmanuel Muteti', 'Emmanuel Muteti'), ('Paul Msava', 'Paul Msava'), ('Kevin Waswa', 'Kevin Waswa')], default='Steven Ogola', max_length=50),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='escalation_type',
            field=models.CharField(choices=[('Proactive', 'Proactive'), ('Reactive', 'Reactive'), ('Interception', 'Interception'), ('Support', 'Support'), ('Optimization', 'Optimization')], max_length=50),
        ),
    ]
