# Generated by Django 5.0.6 on 2024-11-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0006_dispatch_ec_alter_dispatch_escalation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='msp',
            field=models.CharField(choices=[('None', 'None'), ('Egypro', 'Egypro'), ('Camusat', 'Camusat'), ('Adrian', 'Adrian'), ('Kinde', 'Kinde'), ('Fireside', 'Fireside'), ('Soliton', 'Soliton')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='rp',
            field=models.CharField(choices=[('None', 'None'), ('Fireside', 'Fireside'), ('Kinde', 'Kinde'), ('Hatikvah', 'Hatikvah'), ('Camusat', 'Camusat'), ('Techminds', 'Techminds'), ('Egypro', 'Egypro'), ('Optimax', 'Optimax'), ('Pavicon', 'Pavicon'), ('Adrian', 'Adrian'), ('Powergen', 'Powergen'), ('Tetranet', 'Tetranet'), ('ACL', 'ACL'), ('Extra Dimensions', 'Extra Dimensions')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='rp_category',
            field=models.CharField(choices=[('None', 'None'), ('Fireside', 'Fireside'), ('Kinde', 'Kinde'), ('Hatikvah', 'Hatikvah'), ('Camusat', 'Camusat'), ('Techminds', 'Techminds'), ('Egypro', 'Egypro'), ('Optimax', 'Optimax'), ('Pavicon', 'Pavicon'), ('Adrian', 'Adrian'), ('Powergen', 'Powergen'), ('Tetranet', 'Tetranet'), ('ACL', 'ACL'), ('Extra Dimensions', 'Extra Dimensions')], default='None', max_length=50, null=True),
        ),
    ]
