# Generated by Django 5.0.6 on 2024-12-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0007_alter_dispatch_msp_alter_dispatch_rp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
