# Generated by Django 5.0.6 on 2024-12-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0008_dispatch_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='is_expired',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
