# Generated by Django 5.0.6 on 2025-01-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0009_dispatch_expired_at_dispatch_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='rp',
            field=models.CharField(choices=[('None', 'None'), ('Fireside', 'Fireside'), ('Kinde', 'Kinde'), ('Hatikvah', 'Hatikvah'), ('Camusat', 'Camusat'), ('Techminds', 'Techminds'), ('Egypro', 'Egypro'), ('Optimax', 'Optimax'), ('Pavicon', 'Pavicon'), ('Decko', 'Decko'), ('Adrian', 'Adrian'), ('Powergen', 'Powergen'), ('Tetranet', 'Tetranet'), ('Extra Dimensions', 'Extra Dimensions')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='rp_category',
            field=models.CharField(choices=[('None', 'None'), ('Fireside', 'Fireside'), ('Kinde', 'Kinde'), ('Hatikvah', 'Hatikvah'), ('Camusat', 'Camusat'), ('Techminds', 'Techminds'), ('Egypro', 'Egypro'), ('Optimax', 'Optimax'), ('Pavicon', 'Pavicon'), ('Decko', 'Decko'), ('Adrian', 'Adrian'), ('Powergen', 'Powergen'), ('Tetranet', 'Tetranet'), ('Extra Dimensions', 'Extra Dimensions')], default='None', max_length=50, null=True),
        ),
    ]
