# Generated by Django 5.0.6 on 2025-02-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0010_alter_dispatch_rp_alter_user_rp_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rp_category',
            field=models.CharField(choices=[('None', 'None'), ('Fireside', 'Fireside'), ('Kinde', 'Kinde'), ('Hatikvah', 'Hatikvah'), ('Camusat', 'Camusat'), ('Techminds', 'Techminds'), ('Egypro', 'Egypro'), ('Optimax', 'Optimax'), ('Pavicon', 'Pavicon'), ('Decko', 'Decko'), ('Adrian', 'Adrian'), ('Powergen', 'Powergen'), ('Tetranet', 'Tetranet'), ('Extra Dimensions', 'Extra Dimensions'), ('Quavatel', 'Quavatel'), ('Acl', 'Acl')], default='None', max_length=50, null=True),
        ),
    ]
