# Generated by Django 5.0.6 on 2025-03-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0012_alter_dispatch_rp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='fdp',
            field=models.CharField(choices=[('Fireside', 'Fireside'), ('Broadcom', 'Broadcom'), ('Optimax', 'Optimax'), ('BTN', 'BTN'), ('Com21', 'Com21'), ('Bens', 'Bens'), ('Geonet', 'Geonet')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='fdp_category',
            field=models.CharField(choices=[('None', 'None'), ('Fireside', 'Fireside'), ('Broadcom', 'Broadcom'), ('Optimax', 'Optimax'), ('BTN', 'BTN'), ('Com21', 'Com21'), ('Bens', 'Bens'), ('Geonet', 'Geonet')], default='None', max_length=50, null=True),
        ),
    ]
