# Generated by Django 5.0.6 on 2026-01-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0013_alter_dispatch_fdp_alter_user_fdp_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='ec',
            field=models.CharField(choices=[('Steven Ogola', 'Steven Ogola'), ('Emmanuel Muteti', 'Emmanuel Muteti'), ('Paul Msava', 'Paul Msava'), ('Kevin Waswa', 'Kevin Waswa'), ('John Wathinja', 'John Wathinja'), ('Joel Obedi', 'Joel Obedi'), ('Susan Terer', 'Susan Terer'), ('Duncan Ndirangu', 'Duncan Ndirangu')], default='Steven Ogola', max_length=50),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='fdp',
            field=models.CharField(choices=[('Fireside', 'Fireside'), ('Broadcom', 'Broadcom'), ('Optimax', 'Optimax'), ('BTN', 'BTN'), ('Com21', 'Com21'), ('Fireside Coast', 'Fireside Coast'), ('Geonet', 'Geonet')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='msp',
            field=models.CharField(choices=[('None', 'None'), ('Egypro', 'Egypro'), ('Camusat', 'Camusat'), ('Adrian', 'Adrian'), ('Kinde', 'Kinde'), ('Fireside', 'Fireside'), ('Soliton', 'Soliton'), ('Sovereign', 'Sovereign')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fdp_category',
            field=models.CharField(choices=[('None', 'None'), ('Fireside', 'Fireside'), ('Broadcom', 'Broadcom'), ('Optimax', 'Optimax'), ('BTN', 'BTN'), ('Com21', 'Com21'), ('Fireside Coast', 'Fireside Coast'), ('Geonet', 'Geonet')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='msp_category',
            field=models.CharField(choices=[('None', 'None'), ('Egypro', 'Egypro'), ('Camusat', 'Camusat'), ('Adrian', 'Adrian'), ('Kinde', 'Kinde'), ('Fireside', 'Fireside'), ('Soliton', 'Soliton'), ('Sovereign', 'Sovereign')], default='None', max_length=50, null=True),
        ),
    ]
