# Generated by Django 5.0.6 on 2026-09-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0014_alter_dispatch_ec_alter_dispatch_fdp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='msp',
            field=models.CharField(choices=[('None', 'None'), ('Egypro', 'Egypro'), ('Camusat', 'Camusat'), ('Adrian', 'Adrian'), ('Kinde', 'Kinde'), ('Fireside', 'Fireside'), ('Soliton', 'Soliton'), ('Sovereign', 'Sovereign'), ('Optimax', 'Optimax'), ('Tetranet', 'Tetranet'), ('Corevantage', 'Corevantage')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='msp_category',
            field=models.CharField(choices=[('None', 'None'), ('Egypro', 'Egypro'), ('Camusat', 'Camusat'), ('Adrian', 'Adrian'), ('Kinde', 'Kinde'), ('Fireside', 'Fireside'), ('Soliton', 'Soliton'), ('Sovereign', 'Sovereign'), ('Optimax', 'Optimax'), ('Tetranet', 'Tetranet'), ('Corevantage', 'Corevantage')], default='None', max_length=50, null=True),
        ),
    ]
