# Generated by Django 5.0.6 on 2026-09-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0015_alter_dispatch_msp_alter_user_msp_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='stage',
            field=models.CharField(choices=[('Survey', 'Survey'), ('Design', 'Design'), ('Design approval', 'Design approval'), ('Commercial approval', 'Commercial approval'), ('Po issuance', 'Po issuance'), ('Materials', 'Materials'), ('Deployment', 'Deployment'), ('Interception', 'Interception'), ('On hold', 'On hold'), ('Dropped', 'Dropped')], default='Survey', max_length=50),
        ),
    ]
