# Generated by Django 5.0.6 on 2026-09-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0017_dispatchstagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='ceo_sla_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='coo_sla_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='cto_sla_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='hod_sla_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='pm_sla_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
