# Generated by Django 5.0.6 on 2026-09-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0018_dispatch_ceo_sla_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='escalation_type',
            field=models.CharField(choices=[('Proactive', 'Proactive'), ('Reactive', 'Reactive'), ('Interception', 'Interception'), ('Support', 'Support'), ('Optimization', 'Optimization'), ('OTB', 'OTB')], max_length=50),
        ),
    ]
