# Generated by Django 5.0.6 on 2026-09-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0019_alter_dispatch_escalation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch',
            old_name='ceo_sla_email_sent',
            new_name='ceo_sla_email_sent_normal',
        ),
        migrations.RenameField(
            model_name='dispatch',
            old_name='coo_sla_email_sent',
            new_name='ceo_sla_email_sent_optimization',
        ),
        migrations.RenameField(
            model_name='dispatch',
            old_name='cto_sla_email_sent',
            new_name='ceo_sla_email_sent_otb',
        ),
        migrations.RenameField(
            model_name='dispatch',
            old_name='hod_sla_email_sent',
            new_name='coo_sla_email_sent_normal',
        ),
        migrations.RenameField(
            model_name='dispatch',
            old_name='pm_sla_email_sent',
            new_name='coo_sla_email_sent_optimization',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='coo_sla_email_sent_otb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='cto_sla_email_sent_normal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='cto_sla_email_sent_optimization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='cto_sla_email_sent_otb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='hod_sla_email_sent_normal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='hod_sla_email_sent_optimization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='hod_sla_email_sent_otb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='pm_sla_email_sent_normal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='pm_sla_email_sent_optimization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='pm_sla_email_sent_otb',
            field=models.BooleanField(default=False),
        ),
    ]
