# Generated by Django 5.0.6 on 2026-09-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0020_rename_ceo_sla_email_sent_dispatch_ceo_sla_email_sent_normal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='rp',
            field=models.CharField(choices=[('None', 'None'), ('Fireside', 'Fireside'), ('Kinde', 'Kinde'), ('Hatikvah', 'Hatikvah'), ('Camusat', 'Camusat'), ('Techminds', 'Techminds'), ('Egypro', 'Egypro'), ('Optimax', 'Optimax'), ('Pavicon', 'Pavicon'), ('Decko', 'Decko'), ('Adrian', 'Adrian'), ('Powergen', 'Powergen'), ('Tetranet', 'Tetranet'), ('Extra Dimensions', 'Extra Dimensions'), ('Quavatel', 'Quavatel'), ('Acl', 'Acl')], default=None, max_length=50, null=True),
        ),
    ]
