# Generated by Django 5.0.6 on 2026-10-03 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0021_alter_dispatch_rp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchStageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_stage_comments', to=settings.AUTH_USER_MODEL)),
                ('stage_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mashauri.dispatchstagehistory')),
            ],
            options={
                'verbose_name': 'Dispatch Stage Comment',
                'verbose_name_plural': 'Dispatch Stage Comments',
                'db_table': 'mashauri_dispatch_stage_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
