# Generated by Django 5.0.6 on 2026-10-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0022_dispatchstagecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchstagecomment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='dispatch_stage_comments/'),
        ),
        migrations.AddField(
            model_name='dispatchstagehistory',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='dispatch_stage_history/'),
        ),
    ]
