# Generated by Django 5.0.6 on 2026-10-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0023_dispatchstagecomment_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchstagehistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchstagehistory',
            name='duration_seconds',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchstagehistory',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
