# Generated by Django 5.0.6 on 2026-10-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashauri', '0025_alter_dispatch_rp_alter_user_rp_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='stage',
            field=models.CharField(choices=[('Survey', 'Survey'), ('Design', 'Design'), ('Design approval', 'Design approval'), ('Commercial approval', 'Commercial approval'), ('OSH', 'OSH'), ('Po issuance', 'Po issuance'), ('Materials', 'Materials'), ('Deployment', 'Deployment'), ('Interception', 'Interception'), ('On hold', 'On hold'), ('Dropped', 'Dropped')], default='Survey', max_length=50),
        ),
    ]
